export enum QuestionSubject {
  Contacts = "Contacts",
  Keeper = "Keeper",
  FieldsAndEquipment = "FieldsAndEquipment",
  OutOfBoundaries = "OutOfBoundaries",
  Process = "Process",
  DelayOfGame = "DelayOfGame",
  Definition = "Definition",
  Advantage = "Advantage",
  DelayedPenalty = "DelayedPenalty",
  Scoring = "Scoring",
  SnitchPlay = "SnitchPlay",
  ImmunityAndGuarding = "ImmunityAndGuarding",
  Reset = "Reset",
  Substitution = "Substitution",
  NHNF = "NHNF",
  KO = "KO",
  Other = "Other",
  BallInteraction = "BallInteraction",
  Assistref = "Assistref",
  Snitchref = "Snitchref",
  Headref = "Headref"
}